=== Moroccan-Ghost/rapport-xml/rapport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="rapport">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element type='TYPE_MANDAT' name='mandat' maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="TYPE_MANDAT">
        <xsd:sequence>
            <xsd:element type="TYPE_PERSONNE" name='expediteur' maxOccurs="1"></xsd:element>
            <xsd:element type="TYPE_PERSONNE" name='destinataire' maxOccurs="1"></xsd:element>
        </xsd:sequence>
        <xsd:attribute type="xsd:ID" name="num" use='required'></xsd:attribute>
        <xsd:attribute type="xsd:date" name="date" use="required"></xsd:attribute>
        <xsd:attribute type="xsd:float" name="montant" use="required"></xsd:attribute>
        <xsd:attribute name="etat">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="recu"></xsd:enumeration>
                    <xsd:enumeration value="nonRecu"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="TYPE_PERSONNE">
        <xsd:attribute name='cin' type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name='nom' type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name='prenom' type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name='ville' type="xsd:string" use="required"></xsd:attribute>      
    </xsd:complexType>

</xsd:schema>

=== Moroccan-Ghost/rapport-xml/rapport.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rapport.xsd">
    <mandat num="M0" date="2007-01-01" montant="10000" etat="recu">
        <expediteur cin="A123" nom="slimani" prenom="youssef" ville="casa"/>
        <destinataire cin="B123" nom="hassouni" prenom="laila" ville="fes"/>
    </mandat>
    <mandat num="M1" date="2010-05-11" montant="2100" etat="nonRecu">
        <expediteur cin="A546" nom="Alaoui" prenom="ali" ville="meknes"/>
        <destinataire cin="B1443" nom="Alaoui" prenom="laila" ville="tanger"/>
    </mandat>
    <mandat num="M2" date="2022-11-11" montant="500" etat="recu">
        <expediteur cin="C123" nom="qasmi" prenom="yassin" ville="kenitra"/>
        <destinataire cin="D123" nom="hassouni" prenom="ahmed" ville="rabat"/>
    </mandat>
</rapport>
